replicaCount: 1
revisionHistoryLimit: 3

image:
  repository: 590183865331.dkr.ecr.ap-northeast-2.amazonaws.com/plotting-user-app
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

namespace: dev

resources:
  limits:
    cpu: 250m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 256Mi
